import SectionHeader from "@/components/Headings/SectionHeader";
import { Badge } from "@/components/ui/badge";
import { Eyebrow, Body, Muted, CardTitle } from "@/components/ui/typography";
import { cn } from "@/lib/utils";
import Image from "next/image";
import AxiomCard from "@/components/homesections/AxiomCard";

const AGENTS = [
  {
    name: "Axiom",
    role: "Lead AI Agent",
    department: "Head of the AI Team",
    imageSrc: "/images/agents/Axiom.jpeg",
    languages: [
      "English",
      "Hindi",
      "Spanish",
      "Portuguese",
      "Arabic",
      "Mandarin",
      "+ more",
    ],
    languageLabel: "All languages",
    accent: "from-primary to-brand-purple",
    glow: "bg-primary",
    isPrimary: true,
    topLine: "via-primary/50",
    border: "hover:border-primary/25",
    tag: "text-primary/70",
    pill: "Primary AI voice",
    function:
      "Axiom is the leader of the OX AI agent team. He coordinates the six agents that operate across the OX platform, ensuring the digital ecosystem functions with precision and purpose. Axiom is the primary AI voice of the OX network — the agent who introduces the platform, represents the team, and communicates the OX mission to the world.",
  },
  {
    name: "Olivia Verma",
    role: "Verification Agent",
    department: "Network Integrity",
    imageSrc: "/images/agents/Olivia.jpeg",
    languages: ["English"],
    languageLabel: "English",
    accent: "from-brand-purple to-primary",
    glow: "bg-brand-purple",
    isPrimary: false,
    topLine: "via-brand-purple/50",
    border: "hover:border-brand-purple/25",
    tag: "text-brand-purple/80",
    function:
      "X2 is responsible for the integrity of every verified outcome on the OX network. It confirms that human contributions meet the standards required before any reward is issued. X2 operates on-chain, ensuring the verification process is transparent, immutable, and tamper-proof.",
  },
  {
    name: "Aarav Knox",
    role: "Intelligence Layer Agent",
    department: "Organisational Insight",
    imageSrc: "/images/agents/Aarav.jpeg",
    languages: ["Hindi"],
    languageLabel: "Hindi",
    accent: "from-primary to-brand-purple",
    glow: "bg-primary",
    isPrimary: true,
    topLine: "via-primary/50",
    border: "hover:border-primary/25",
    tag: "text-primary/70",
    function:
      "X3 processes anonymised intelligence signals generated by the network and translates them into structured, actionable insight for organisations. It never accesses individual Machine Self data — it works exclusively with aggregated, consent-gated outputs. X3 is the bridge between human intelligence and organisational demand.",
  },
  {
    name: "Miguel Santos",
    role: "Token Economy Agent",
    department: "Protocol Stability",
    imageSrc: "/images/agents/Miguel.jpeg",
    languages: ["Portuguese"],
    languageLabel: "Portuguese",
    accent: "from-brand-purple to-primary",
    glow: "bg-brand-purple",
    isPrimary: false,
    topLine: "via-brand-purple/50",
    border: "hover:border-brand-purple/25",
    tag: "text-brand-purple/80",
    function:
      "X4 monitors the health of the OXIT and OXME token economy in real time. It tracks emission rates, conversion activity, and network participation levels to support protocol stability. X4 does not control or alter the fixed supply — it observes and reports only.",
  },
  {
    name: "Sofia Reyes",
    role: "Governance Agent",
    department: "Decentralised Governance",
    imageSrc: "/images/agents/Sofia.jpeg",
    languages: ["Spanish"],
    languageLabel: "Spanish",
    accent: "from-primary to-brand-purple",
    glow: "bg-primary",
    isPrimary: true,
    topLine: "via-primary/50",
    border: "hover:border-primary/25",
    tag: "text-primary/70",
    function:
      "X5 supports the decentralised governance layer of the OX protocol. It tracks proposals, participation rates, and network-level decisions, ensuring the governance process remains transparent and accessible to all verified participants. X5 has no voting power of its own — it serves the network, not the protocol.",
  },
  {
    name: "Zyan",
    role: "Security & Privacy Agent",
    department: "Network Sentinel",
    imageSrc: "/images/agents/Zayn.jpeg",
    languages: ["English"],
    languageLabel: "English",
    accent: "from-brand-purple to-primary",
    glow: "bg-brand-purple",
    isPrimary: false,
    topLine: "via-brand-purple/50",
    border: "hover:border-brand-purple/25",
    tag: "text-brand-purple/80",
    function:
      "X6 is the sentinel of the OX network. It monitors for anomalies, verifies that zero-knowledge proof systems are functioning correctly, and ensures that no data ever leaves a user's device without explicit consent. X6 is the last line of defence for every Machine Self on the network.",
  },
];

function LanguageBadge({
  languages,
  isAxiom = false,
  isPrimary = true,
}: {
  languages: string[];
  isAxiom?: boolean;
  isPrimary?: boolean;
}) {
  return (
    <div className="flex flex-wrap gap-1.5">
      {isAxiom ? (
        <>
          {languages.map((lang) => (
            <Badge
              key={lang}
              variant="outline"
              className="border-white/10 bg-white/[0.05] text-foreground/50 font-semibold tracking-wide"
            >
              {lang}
            </Badge>
          ))}
        </>
      ) : (
        <Badge
          variant="outline"
          className={cn(
            "text-[10px] font-bold uppercase tracking-[0.2em]",
            isPrimary
              ? "border-primary/30 bg-primary/[0.10] text-primary/90"
              : "border-brand-purple/30 bg-brand-purple/[0.10] text-brand-purple/90"
          )}
        >
          {languages[0]}
        </Badge>
      )}
    </div>
  );
}

export default function AiTeamSection() {
  const axiom = AGENTS[0];
  const row2 = AGENTS.slice(1, 3);
  const row3 = AGENTS.slice(3);

  return (
    <section className="relative mx-auto flex w-full max-w-6xl flex-col gap-14 px-6 py-24 text-white">
      <div
        aria-hidden
        className="atm-green-blue pointer-events-none absolute inset-0 -z-10"
      />

      <SectionHeader
        title="The AI team."
        eyebrowText="THE TEAM"
        subtitle="Six dedicated AI agents operating across coordination, verification, and intelligence — each serving a specific function within the OX ecosystem."
      />

      {/* ── AXIOM — hero card with video play button ── */}
      <AxiomCard axiom={axiom} />

      {/* ── ROW 2: Olivia + Aarav — image fills full card height ── */}
      <div className="grid gap-4 lg:grid-cols-2">
        {row2.map((a) => {
          return (
            <div
              key={a.name}
              className={cn("glass-card group relative overflow-hidden transition-all duration-300", a.border)}
            >
              <div
                className={cn("absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent to-transparent", a.topLine)}
              />
              <div
                className={cn("pointer-events-none absolute -right-12 -top-12 h-48 w-48 rounded-full opacity-[0.06] blur-3xl transition-opacity duration-500 group-hover:opacity-[0.13]", a.glow)}
              />

              {/* Portrait on top, info below — consistent with Row 3 */}
              <div className="relative flex flex-col">
                <div className="relative aspect-square w-full overflow-hidden">
                  <Image
                    src={a.imageSrc}
                    alt={a.name}
                    fill
                    className="object-cover object-bottom transition-transform duration-500 group-hover:scale-105"
                  />
                </div>

                <div className="flex flex-col gap-4 p-6">
                  <div>
                    <Eyebrow className={cn(a.tag)}>{a.role}</Eyebrow>
                    <CardTitle
                      className={cn("mt-1.5 bg-gradient-to-r bg-clip-text leading-none tracking-tight text-transparent", a.accent)}
                    >
                      {a.name}
                    </CardTitle>
                    <Muted className="mt-1">{a.department}</Muted>
                  </div>

                  <div className="h-px bg-gradient-to-r from-transparent via-white/[0.07] to-transparent" />

                  <Body className="text-foreground/70">{a.function}</Body>

                  <div className="h-px bg-gradient-to-r from-transparent via-white/[0.07] to-transparent" />

                  <div>
                    <Eyebrow className="mb-2">Language</Eyebrow>
                    <LanguageBadge
                      languages={a.languages}
                      isPrimary={a.isPrimary}
                    />
                  </div>
                </div>
              </div>
            </div>
          );
        })}
      </div>

      {/* ── ROW 3: Miguel + Sofia + Zyan — portrait top, info below ── */}
      <div className="grid gap-4 lg:grid-cols-3">
        {row3.map((a) => {
          return (
            <div
              key={a.name}
              className={cn("glass-card group relative overflow-hidden transition-all duration-300", a.border)}
            >
              <div
                className={cn("absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent to-transparent", a.topLine)}
              />
              <div
                className={cn("pointer-events-none absolute -right-10 -top-10 h-40 w-40 rounded-full opacity-[0.06] blur-3xl transition-opacity duration-500 group-hover:opacity-[0.13]", a.glow)}
              />

              <div className="relative flex flex-col">
                {/* Portrait — 3/4 ratio, no side padding so it edge-to-edge */}
                <div className="relative aspect-[3/4] w-full overflow-hidden">
                  <Image
                    src={a.imageSrc}
                    alt={a.name}
                    fill
                    className="object-cover object-top transition-transform duration-500 group-hover:scale-105"
                  />
                </div>

                {/* Info below */}
                <div className="flex flex-col gap-4 p-6">
                  <div>
                    <Eyebrow className={cn(a.tag)}>{a.role}</Eyebrow>
                    <CardTitle
                      className={cn("mt-1.5 bg-gradient-to-r bg-clip-text leading-none tracking-tight text-transparent", a.accent)}
                    >
                      {a.name}
                    </CardTitle>
                    <Muted className="mt-0.5">{a.department}</Muted>
                  </div>

                  <div className="h-px bg-gradient-to-r from-transparent via-white/[0.07] to-transparent" />

                  <Body className="text-foreground/70">
                    {a.function}
                  </Body>

                  <div className="h-px bg-gradient-to-r from-transparent via-white/[0.07] to-transparent" />

                  <div>
                    <Eyebrow className="mb-2">Language</Eyebrow>
                    <LanguageBadge
                      languages={a.languages}
                      isPrimary={a.isPrimary}
                    />
                  </div>
                </div>
              </div>
            </div>
          );
        })}
      </div>
    </section>
  );
}
