import SectionHeader from "@/components/Headings/SectionHeader";
import Image from "next/image";

const AGENTS = [
  {
    name: "Axiom",
    role: "Lead AI Agent",
    department: "Head of the AI Team",
    imageSrc: "/images/agents/Axiom.jpeg",
    languages: [
      "English",
      "Hindi",
      "Spanish",
      "Portuguese",
      "Arabic",
      "Mandarin",
      "+ more",
    ],
    languageLabel: "All languages",
    accent: "from-[#FF2D6B] to-[#7B1FA2]",
    glow: "bg-[#FF2D6B]",
    glowHex: "rgba(255,45,107,0.15)",
    topLine: "via-[#FF2D6B]/50",
    border: "hover:border-[#FF2D6B]/25",
    tag: "text-[#FF2D6B]/70",
    pill: "Primary AI voice",
    function:
      "Axiom is the leader of the OX AI agent team. He coordinates the six agents that operate across the OX platform, ensuring the digital ecosystem functions with precision and purpose. Axiom is the primary AI voice of the OX network — the agent who introduces the platform, represents the team, and communicates the OX mission to the world.",
  },
  {
    name: "Olivia Verma",
    role: "Verification Agent",
    department: "Network Integrity",
    imageSrc: "/images/agents/Olivia.jpeg",
    languages: ["English"],
    languageLabel: "English",
    accent: "from-[#7B1FA2] to-[#FF2D6B]",
    glow: "bg-[#7B1FA2]",
    glowHex: "rgba(123,31,162,0.15)",
    topLine: "via-[#7B1FA2]/50",
    border: "hover:border-[#7B1FA2]/25",
    tag: "text-[#7B1FA2]/80",
    function:
      "X2 is responsible for the integrity of every verified outcome on the OX network. It confirms that human contributions meet the standards required before any reward is issued. X2 operates on-chain, ensuring the verification process is transparent, immutable, and tamper-proof.",
  },
  {
    name: "Aarav Knox",
    role: "Intelligence Layer Agent",
    department: "Organisational Insight",
    imageSrc: "/images/agents/Aarav.jpeg",
    languages: ["Hindi"],
    languageLabel: "Hindi",
    accent: "from-[#FF2D6B] to-[#7B1FA2]",
    glow: "bg-[#FF2D6B]",
    glowHex: "rgba(255,45,107,0.15)",
    topLine: "via-[#FF2D6B]/50",
    border: "hover:border-[#FF2D6B]/25",
    tag: "text-[#FF2D6B]/70",
    function:
      "X3 processes anonymised intelligence signals generated by the network and translates them into structured, actionable insight for organisations. It never accesses individual Machine Self data — it works exclusively with aggregated, consent-gated outputs.",
  },
  {
    name: "Miguel Santos",
    role: "Token Economy Agent",
    department: "Protocol Stability",
    imageSrc: "/images/agents/Miguel.jpeg",
    languages: ["Portuguese"],
    languageLabel: "Portuguese",
    accent: "from-[#7B1FA2] to-[#FF2D6B]",
    glow: "bg-[#7B1FA2]",
    glowHex: "rgba(123,31,162,0.15)",
    topLine: "via-[#7B1FA2]/50",
    border: "hover:border-[#7B1FA2]/25",
    tag: "text-[#7B1FA2]/80",
    function:
      "X4 monitors the health of the OXIT and OXME token economy in real time. It tracks emission rates, conversion activity, and network participation levels to support protocol stability. X4 does not control or alter the fixed supply — it observes and reports only.",
  },
  {
    name: "Sofia Reyes",
    role: "Governance Agent",
    department: "Decentralised Governance",
    imageSrc: "/images/agents/Sofia.jpeg",
    languages: ["Spanish"],
    languageLabel: "Spanish",
    accent: "from-[#FF2D6B] to-[#7B1FA2]",
    glow: "bg-[#FF2D6B]",
    glowHex: "rgba(255,45,107,0.15)",
    topLine: "via-[#FF2D6B]/50",
    border: "hover:border-[#FF2D6B]/25",
    tag: "text-[#FF2D6B]/70",
    function:
      "X5 supports the decentralised governance layer of the OX protocol. It tracks proposals, participation rates, and network-level decisions, ensuring the governance process remains transparent and accessible to all verified participants.",
  },
  {
    name: "Zyan",
    role: "Security & Privacy Agent",
    department: "Network Sentinel",
    imageSrc: "/images/agents/Zayn.jpeg",
    languages: ["English"],
    languageLabel: "English",
    accent: "from-[#7B1FA2] to-[#FF2D6B]",
    glow: "bg-[#7B1FA2]",
    glowHex: "rgba(123,31,162,0.15)",
    topLine: "via-[#7B1FA2]/50",
    border: "hover:border-[#7B1FA2]/25",
    tag: "text-[#7B1FA2]/80",
    function:
      "X6 is the sentinel of the OX network. It monitors for anomalies, verifies that zero-knowledge proof systems are functioning correctly, and ensures that no data ever leaves a user's device without explicit consent.",
  },
];

function LanguageBadge({
  languages,
  isAxiom = false,
  accentColor,
}: {
  languages: string[];
  isAxiom?: boolean;
  accentColor: string;
}) {
  return (
    <div className="flex flex-wrap gap-1.5">
      {isAxiom ? (
        <>
          {languages.map((lang) => (
            <span
              key={lang}
              className="rounded-full border border-white/10 bg-white/[0.05] px-2.5 py-1 text-[10px] font-semibold tracking-[0.12em] text-white/50"
            >
              {lang}
            </span>
          ))}
        </>
      ) : (
        <span
          className="rounded-full px-3 py-1 text-[10px] font-bold uppercase tracking-[0.2em]"
          style={{
            border: `1px solid ${accentColor}30`,
            background: `${accentColor}10`,
            color: `${accentColor}90`,
          }}
        >
          {languages[0]}
        </span>
      )}
    </div>
  );
}

export default function AiTeamSection() {
  const axiom = AGENTS[0];
  const row2 = AGENTS.slice(1, 3);
  const row3 = AGENTS.slice(3);

  return (
    <section className="relative mx-auto flex w-full max-w-6xl flex-col gap-14 px-6 py-24 text-white sm:py-32">
      <div
        aria-hidden
        className="pointer-events-none absolute inset-0 -z-10 [background-image:radial-gradient(ellipse_70%_50%_at_20%_10%,rgba(255,45,107,0.14),transparent_65%),radial-gradient(ellipse_55%_45%_at_80%_90%,rgba(123,31,162,0.12),transparent_65%)]"
      />

      <SectionHeader
        pillText="AI Team"
        title="The AI team."
        subtitle="Six dedicated AI agents operating across coordination, verification, and intelligence — each serving a specific function within the OX ecosystem."
      />

      {/* ── AXIOM — hero, image fills full card height ── */}
      <div
        className={`group relative overflow-hidden rounded-3xl border border-white/[0.07] bg-gradient-to-br from-[#FF2D6B]/[0.06] to-[#7B1FA2]/[0.03] transition-all duration-300 ${axiom.border}`}
      >
        <div className="pointer-events-none absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-[#FF2D6B]/60 to-transparent" />
        <div className="pointer-events-none absolute -left-20 -top-20 h-80 w-80 rounded-full bg-[#FF2D6B] opacity-[0.07] blur-[90px]" />
        <div className="pointer-events-none absolute -bottom-20 -right-20 h-80 w-80 rounded-full bg-[#7B1FA2] opacity-[0.07] blur-[90px]" />

        <div className="relative grid lg:grid-cols-[420px_1px_1fr]">
          {/* Image — stretches full card height, no padding */}
          <div className="relative min-h-[520px] overflow-hidden lg:min-h-0">
            <Image
              src={axiom.imageSrc}
              alt={axiom.name}
              fill
              className="object-cover object-top"
            />
          </div>

          {/* Vertical divider */}
          <div className="hidden bg-gradient-to-b from-transparent via-white/[0.07] to-transparent lg:block" />

          {/* Info */}
          <div className="flex flex-col justify-center gap-7 p-8 lg:p-10">
            <div>
              <span
                className={`text-[11px] font-bold uppercase tracking-[0.28em] ${axiom.tag}`}
              >
                {axiom.role}
              </span>
              <h3
                className={`mt-2 bg-gradient-to-r ${axiom.accent} bg-clip-text text-[52px] font-black leading-none tracking-[-0.05em] text-transparent sm:text-[60px]`}
              >
                {axiom.name}
              </h3>
              <p className="mt-2 text-[14px] text-white/35">
                {axiom.department}
              </p>
            </div>

            <div className="h-px bg-gradient-to-r from-transparent via-white/[0.08] to-transparent" />

            <div>
              <p className="mb-3 text-[10px] font-bold uppercase tracking-[0.28em] text-white/25">
                Function
              </p>
              <p className="text-[17px] leading-[1.9] text-white/65 sm:text-[18px]">
                {axiom.function}
              </p>
            </div>

            <div className="h-px bg-gradient-to-r from-transparent via-white/[0.08] to-transparent" />

            {/* Languages */}
            <div>
              <p className="mb-3 text-[10px] font-bold uppercase tracking-[0.28em] text-white/25">
                Languages
              </p>
              <LanguageBadge
                languages={axiom.languages}
                isAxiom
                accentColor="#FF2D6B"
              />
            </div>

            <div className="inline-flex w-fit items-center gap-2.5 rounded-full border border-[#FF2D6B]/20 bg-[#FF2D6B]/[0.07] px-5 py-2.5 text-[12px] font-bold uppercase tracking-[0.22em] text-[#FF2D6B]/70">
              <span className="h-2 w-2 animate-pulse rounded-full bg-[#FF2D6B] shadow-[0_0_6px_rgba(255,45,107,0.9)]" />
              Primary AI voice
            </div>
          </div>
        </div>
      </div>

      {/* ── ROW 2: Olivia + Aarav — image fills full card height ── */}
      <div className="grid gap-4 lg:grid-cols-2">
        {row2.map((a) => {
          const accentHex = a.glow === "bg-[#FF2D6B]" ? "#FF2D6B" : "#7B1FA2";
          return (
            <div
              key={a.name}
              className={`group relative overflow-hidden rounded-3xl border border-white/[0.07] bg-gradient-to-br from-white/[0.04] to-transparent transition-all duration-300 ${a.border}`}
            >
              <div
                className={`absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent ${a.topLine} to-transparent`}
              />
              <div
                className={`pointer-events-none absolute -right-12 -top-12 h-48 w-48 rounded-full ${a.glow} opacity-[0.06] blur-3xl transition-opacity duration-500 group-hover:opacity-[0.13]`}
              />

              {/* Side-by-side: image left fills full height, info right */}
              <div className="relative grid grid-cols-[1px] lg:grid-cols-[260px_1px_1fr]">
                {/* Portrait — full card height, no padding, no rounding trim */}
                <div className="relative hidden min-h-[460px] overflow-hidden lg:block">
                  <Image
                    src={a.imageSrc}
                    alt={a.name}
                    fill
                    className="object-cover object-top"
                  />
                </div>

                {/* Mobile portrait (aspect ratio fallback) */}
                <div
                  className="relative w-full overflow-hidden lg:hidden"
                  style={{ aspectRatio: "3/2" }}
                >
                  <Image
                    src={a.imageSrc}
                    alt={a.name}
                    fill
                    className="object-cover object-top"
                  />
                </div>

                {/* Divider */}
                <div className="hidden bg-gradient-to-b from-transparent via-white/[0.06] to-transparent lg:block" />

                {/* Info */}
                <div className="flex flex-col justify-center gap-5 p-7">
                  <div>
                    <span
                      className={`text-[10px] font-bold uppercase tracking-[0.26em] ${a.tag}`}
                    >
                      {a.role}
                    </span>
                    <h3
                      className={`mt-1.5 bg-gradient-to-r ${a.accent} bg-clip-text text-[32px] font-black leading-none tracking-[-0.04em] text-transparent sm:text-[36px]`}
                    >
                      {a.name}
                    </h3>
                    <p className="mt-1 text-[12px] text-white/30">
                      {a.department}
                    </p>
                  </div>

                  <div className="h-px bg-gradient-to-r from-transparent via-white/[0.07] to-transparent" />

                  <p className="text-[15px] leading-[1.85] text-white/55 sm:text-[16px]">
                    {a.function}
                  </p>

                  <div className="h-px bg-gradient-to-r from-transparent via-white/[0.07] to-transparent" />

                  <div>
                    <p className="mb-2 text-[10px] font-bold uppercase tracking-[0.24em] text-white/22">
                      Language
                    </p>
                    <LanguageBadge
                      languages={a.languages}
                      accentColor={accentHex}
                    />
                  </div>
                </div>
              </div>
            </div>
          );
        })}
      </div>

      {/* ── ROW 3: Miguel + Sofia + Zyan — portrait top, info below ── */}
      <div className="grid gap-4 lg:grid-cols-3">
        {row3.map((a) => {
          const accentHex = a.glow === "bg-[#FF2D6B]" ? "#FF2D6B" : "#7B1FA2";
          return (
            <div
              key={a.name}
              className={`group relative overflow-hidden rounded-3xl border border-white/[0.07] bg-gradient-to-br from-white/[0.04] to-transparent transition-all duration-300 ${a.border}`}
            >
              <div
                className={`absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent ${a.topLine} to-transparent`}
              />
              <div
                className={`pointer-events-none absolute -right-10 -top-10 h-40 w-40 rounded-full ${a.glow} opacity-[0.06] blur-3xl transition-opacity duration-500 group-hover:opacity-[0.13]`}
              />

              <div className="relative flex flex-col">
                {/* Portrait — 3/4 ratio, no side padding so it edge-to-edge */}
                <div
                  className="relative w-full overflow-hidden"
                  style={{ aspectRatio: "3/4" }}
                >
                  <Image
                    src={a.imageSrc}
                    alt={a.name}
                    fill
                    className="object-cover object-top"
                  />
                </div>

                {/* Info below */}
                <div className="flex flex-col gap-4 p-6">
                  <div>
                    <span
                      className={`text-[10px] font-bold uppercase tracking-[0.24em] ${a.tag}`}
                    >
                      {a.role}
                    </span>
                    <h3
                      className={`mt-1.5 bg-gradient-to-r ${a.accent} bg-clip-text text-[26px] font-black leading-none tracking-[-0.04em] text-transparent sm:text-[28px]`}
                    >
                      {a.name}
                    </h3>
                    <p className="mt-0.5 text-[12px] text-white/28">
                      {a.department}
                    </p>
                  </div>

                  <div className="h-px bg-gradient-to-r from-transparent via-white/[0.07] to-transparent" />

                  <p className="text-[13.5px] leading-[1.85] text-white/52 sm:text-[14px]">
                    {a.function}
                  </p>

                  <div className="h-px bg-gradient-to-r from-transparent via-white/[0.07] to-transparent" />

                  <div>
                    <p className="mb-2 text-[10px] font-bold uppercase tracking-[0.22em] text-white/22">
                      Language
                    </p>
                    <LanguageBadge
                      languages={a.languages}
                      accentColor={accentHex}
                    />
                  </div>
                </div>
              </div>
            </div>
          );
        })}
      </div>
    </section>
  );
}
