import SectionHeader from "@/components/Headings/SectionHeader";

const AGENTS = [
  {
    name: "Axiom",
    role: "Lead AI Agent — Head of the AI Team",
    function:
      "Axiom is the leader of the OX AI agent team. He coordinates the six agents that operate across the OX platform, ensuring the digital ecosystem functions with precision and purpose. Axiom is the primary AI voice of the OX network — the agent who introduces the platform, represents the team, and communicates the OX mission to the world.",
    note: "LANGUAGE\nTo be confirmed by founding team.",
  },
  {
    name: "X2",
    role: "Verification Agent",
    function:
      "X2 is responsible for the integrity of every verified outcome on the OX network. It confirms that human contributions meet the standards required before any reward is issued. X2 operates on-chain, ensuring the verification process is transparent, immutable, and tamper-proof.",
    note: "LANGUAGE\nTo be confirmed by founding team.",
  },
  {
    name: "X3",
    role: "Intelligence Layer Agent",
    function:
      "X3 processes the anonymised intelligence signals generated by the network and translates them into structured, actionable insight for organisations. It never accesses individual Machine Self data — it works exclusively with aggregated, consent-gated outputs. X3 is the bridge between human intelligence and organisational demand.",
    note: "LANGUAGE\nTo be confirmed by founding team.",
  },
  {
    name: "X4",
    role: "Token Economy Agent",
    function:
      "X4 monitors the health of the OXIT and OXME token economy in real time. It tracks emission rates, conversion activity, and network participation levels to support protocol stability. X4 does not control or alter the fixed supply — it observes and reports only.",
    note: "LANGUAGE\nTo be confirmed by founding team.",
  },
  {
    name: "X5",
    role: "Governance Agent",
    function:
      "X5 supports the decentralised governance layer of the OX protocol. It tracks proposals, participation rates, and network-level decisions, ensuring the governance process remains transparent and accessible to all verified participants. X5 has no voting power of its own — it serves the network, not the protocol.",
    note: "LANGUAGE\nTo be confirmed by founding team.",
  },
  {
    name: "X6",
    role: "Security and Privacy Agent",
    function:
      "X6 is the sentinel of the OX network. It monitors for anomalies, verifies that zero-knowledge proof systems are functioning correctly, and ensures that no data ever leaves a user's device without explicit consent. X6 is the last line of defence for every Machine Self on the network.",
    note: "LANGUAGE\nTo be confirmed by founding team.",
  },
];

export default function AiTeamSection() {
  return (
    <section className="relative mx-auto flex w-full max-w-6xl flex-col gap-10 px-6 py-20 text-white sm:gap-12 sm:py-24">
      <div
        aria-hidden
        className="pointer-events-none absolute inset-0 -z-10 opacity-80 bg-[radial-gradient(circle_at_top,rgba(129,140,248,0.26),transparent_55%),radial-gradient(circle_at_bottom,rgba(56,189,248,0.18),transparent_60%)]"
      />

      <SectionHeader
        pillText="AI Team"
        title="The AI team"
        subtitle="The OX platform operates with a dedicated team of six AI agents that support coordination, verification, and intelligence operations."
      />

      <p className="text-[13px] leading-relaxed text-white/80 sm:text-[14px]">
        The OX platform operates with a dedicated team of six AI agents. Each
        agent serves a specific function within the digital ecosystem —
        supporting coordination, verification, and intelligence operations
        across the network.
      </p>
      <p className="text-[12px] leading-relaxed text-white/60 sm:text-[13px]">
        NOTE TO DEVELOPER: Each agent below requires a high-quality square
        image. Image slots are marked. Images to be supplied by the founding
        team. Agent names X2–X6 are placeholders. Final names to be confirmed by
        founding team before publishing.
      </p>

      <div className="grid gap-6 md:grid-cols-2">
        {AGENTS.map((agent) => (
          <div
            key={agent.name}
            className="space-y-3 rounded-2xl border border-white/10 bg-black/40 p-5 shadow-[0_20px_70px_rgba(0,0,0,0.7)]"
          >
            <div className="flex items-center gap-4">
              <div className="flex h-14 w-14 items-center justify-center rounded-xl border border-white/20 bg-white/5 text-[11px] text-white/70">
                {/* NOTE TO DEVELOPER: Insert high-quality square image for {agent.name} here. */}
                IMG
              </div>
              <div>
                <p className="text-[14px] font-semibold text-white">
                  {agent.name}
                </p>
                <p className="text-[12px] text-white/60">{agent.role}</p>
              </div>
            </div>
            <p className="text-[13px] leading-relaxed text-white/80 sm:text-[14px]">
              {agent.function}
            </p>
            <p className="whitespace-pre-line text-[12px] leading-relaxed text-white/60 sm:text-[13px]">
              {agent.note}
            </p>
          </div>
        ))}
      </div>

      <p className="mt-2 text-[12px] leading-relaxed text-white/60 sm:text-[13px]">
        NOTE TO DEVELOPER: Link this reference to Section 17 — AI Team.
      </p>
    </section>
  );
}
